### ISSUE TITLE
[Confirmation] Would you like to add the `transform` option?

### ISSUE THREAD

**Issue by macocci7** [artisan-build/prompts#6]
@ProjektGopher I'm going to add [transform](https://github.com/laravel/prompts/pull/156) option to `file-selector-prompt`.
I've already implemented it and opened a [PR](https://github.com/macocci7/file-selector-prompt/pull/7) in my `file-selector-prompt` repository.
I'll merge the PR and release it after the new realease of `laravel/promts` (probably next week).

If you'd like to add `transform` option, I'll implement it in `fileselector` in this repository and update the document.
Please tell me your opinion.

**Comment by ProjektGopher** [comment]
I think that makes sense to include. We'll have to wait for the next release of prompts (as you pointed out), then we'll bump our dependency, but we'll also have to implement all those changes to the `Prompt` abstract class in the original `transform` PR you linked in our `PatchedPrompt` shim.

**Comment by macocci7** [comment]
OK!
I'll implement `transform` option and apply all those changes to the `Prompt` abstract class to the `PatchedPrompt` shim later.
